import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

Deno.serve(async (req) => {
  console.log("aiReorderGuide hit");

  const base44 = createClientFromRequest(req);

  try {
    // Step 1 — Fetch all products that are at or below min stock level
    const allProducts = await base44.asServiceRole.entities.Product.list('-created_date', 100);
    
    const lowStockProducts = allProducts.filter(p => 
      p.quantity_on_hand <= p.min_stock_level && 
      p.status !== 'discontinued'
    );

    if (lowStockProducts.length === 0) {
      return Response.json({ 
        success: true, 
        message: "All products are sufficiently stocked. No reorders needed at this time.",
        orders_created: 0
      });
    }

    console.log(`Found ${lowStockProducts.length} low stock products`);

    // Step 2 — Build product summary for AI
    const productSummary = lowStockProducts.map(p => ({
      name: p.name,
      id: p.id,
      category: p.category,
      quantity_on_hand: p.quantity_on_hand,
      min_stock_level: p.min_stock_level,
      unit_cost: p.unit_cost,
      supplier: p.supplier || 'Unknown Supplier',
      location: p.location || 'Unknown Location',
      expiration_date: p.expiration_date || null
    }));

    // Step 3 — Ask AuraAI to generate reorder recommendations
    const prompt = `You are AuraAI, an intelligent inventory management system for a retail store.

Analyze the following low stock products and generate a prioritized reorder guide.

Low Stock Products:
${JSON.stringify(productSummary, null, 2)}

For each product, recommend:
1. How many units to reorder (suggest at least 2x the min_stock_level)
2. Priority level (HIGH/MEDIUM/LOW) based on how critically low the stock is
3. A brief reason for the priority

Then group the recommendations by supplier.

Respond ONLY in this exact JSON format with no other text:
{
  "summary": "Brief overall summary of the reorder situation",
  "recommendations": [
    {
      "product_id": "id here",
      "product_name": "name here",
      "supplier": "supplier here",
      "quantity_to_order": 0,
      "unit_cost": 0,
      "priority": "HIGH",
      "reason": "reason here"
    }
  ],
  "grouped_by_supplier": {
    "Supplier Name": ["product names here"]
  }
}`;

    const llmResult = await base44.asServiceRole.integrations.Core.InvokeLLM({
      prompt,
      model: 'gemini_3_flash',
      add_context_from_internet: false
    });

    // Step 4 — Parse AI response
    let aiResponse;
    try {
      const cleaned = llmResult.toString().replace(/```json|```/g, '').trim();
      aiResponse = JSON.parse(cleaned);
    } catch (e) {
      console.error("Failed to parse AI response:", e.message);
      return Response.json({ 
        success: false, 
        error: "Failed to parse AI recommendations",
        raw: llmResult.toString()
      }, { status: 500 });
    }

    // Step 5 — Group by supplier and create draft Orders
    const supplierGroups: { [key: string]: any[] } = {};
    
    for (const rec of aiResponse.recommendations) {
      const supplier = rec.supplier || 'Unknown Supplier';
      if (!supplierGroups[supplier]) {
        supplierGroups[supplier] = [];
      }
      supplierGroups[supplier].push({
        product_id: rec.product_id,
        product_name: rec.product_name,
        quantity: rec.quantity_to_order,
        unit_cost: rec.unit_cost || 0
      });
    }

    // Step 6 — Create a draft Order for each supplier
    const ordersCreated = [];
    for (const [supplier, items] of Object.entries(supplierGroups)) {
      const totalCost = items.reduce((sum, item) => sum + (item.quantity * item.unit_cost), 0);
      
      const order = await base44.asServiceRole.entities.Order.create({
        supplier,
        status: 'draft',
        items,
        total_cost: totalCost,
        notes: `Auto-generated by AuraAI Reorder Guide on ${new Date().toLocaleDateString()}. ${aiResponse.summary}`
      });

      ordersCreated.push({ supplier, order_id: order.id, items_count: items.length, total_cost: totalCost });
      console.log(`Created draft order for supplier: ${supplier}`);
    }

    return Response.json({
      success: true,
      summary: aiResponse.summary,
      low_stock_count: lowStockProducts.length,
      orders_created: ordersCreated.length,
      orders: ordersCreated,
      recommendations: aiResponse.recommendations
    });

  } catch (err) {
    console.error("aiReorderGuide error:", err.message);
    return Response.json({ success: false, error: err.message }, { status: 500 });
  }
});