import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { ShoppingCart, Plus, RefreshCw, Sparkles, Package, Truck, Check, X, ChevronDown, ChevronUp, Trash2 } from "lucide-react";
import OrderModal from "../components/orders/OrderModal";
import OrderSheet from "../components/mobile/OrderSheet";
import PullToRefresh from "../components/mobile/PullToRefresh";

const statusStyle = {
  draft: "bg-slate-100 text-slate-600",
  submitted: "bg-blue-100 text-blue-700",
  confirmed: "bg-indigo-100 text-indigo-700",
  shipped: "bg-amber-100 text-amber-700",
  received: "bg-green-100 text-green-700",
  cancelled: "bg-red-100 text-red-700",
};

const nextStatus = {
  draft: "submitted",
  submitted: "confirmed",
  confirmed: "shipped",
  shipped: "received",
};

export default function Orders() {
  const [orders, setOrders] = useState([]);
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [editing, setEditing] = useState(null);
  const [expanded, setExpanded] = useState(null);
  useEffect(() => { loadData(); }, []);

  const loadData = async () => {
    setLoading(true);
    const [o, p] = await Promise.all([
      base44.entities.Order.list("-created_date"),
      base44.entities.Product.list(),
    ]);
    setOrders(o);
    setProducts(p);
    setLoading(false);
  };

  const generateOrder = async () => {
    setGenerating(true);
    const lowStock = products.filter(p =>
      p.quantity_on_hand <= p.min_stock_level && p.status !== "discontinued"
    );

    if (lowStock.length === 0) {
      alert("No products are currently low on stock!");
      setGenerating(false);
      return;
    }

    const result = await base44.integrations.Core.InvokeLLM({
      prompt: `You are an inventory ordering AI assistant. Analyze these low-stock products and generate a reorder suggestion.

Low stock items:
${JSON.stringify(lowStock.map(p => ({
  id: p.id,
  name: p.name,
  quantity_on_hand: p.quantity_on_hand,
  min_stock_level: p.min_stock_level,
  unit_cost: p.unit_cost,
  supplier: p.supplier,
  category: p.category,
})), null, 2)}

Create a reorder list grouped by supplier. For each item, suggest a reorder quantity (typically 2-4x the min_stock_level).
Group items by their supplier field. If supplier is missing, use "General Supplier".`,
      response_json_schema: {
        type: "object",
        properties: {
          orders: {
            type: "array",
            items: {
              type: "object",
              properties: {
                supplier: { type: "string" },
                items: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      product_id: { type: "string" },
                      product_name: { type: "string" },
                      quantity: { type: "number" },
                      unit_cost: { type: "number" },
                    }
                  }
                },
                notes: { type: "string" },
              }
            }
          }
        }
      }
    });

    for (const order of (result.orders || [])) {
      const total = order.items.reduce((sum, i) => sum + (i.quantity * (i.unit_cost || 0)), 0);
      const today = new Date();
      const delivery = new Date(today); delivery.setDate(today.getDate() + 7);
      await base44.entities.Order.create({
        supplier: order.supplier,
        status: "draft",
        items: order.items,
        total_cost: total,
        expected_delivery: delivery.toISOString().split("T")[0],
        notes: order.notes || "Auto-generated by AI",
      });
    }

    setGenerating(false);
    loadData();
  };

  const removeOrder = async (orderId) => {
    if (!confirm("Remove this order? This cannot be undone.")) return;
    await base44.entities.Order.delete(orderId);
    setOrders(orders.filter(o => o.id !== orderId));
  };

  const advanceStatus = async (order) => {
    const next = nextStatus[order.status];
    if (!next) return;
    if (next === "received") {
      // Update product quantities
      for (const item of (order.items || [])) {
        if (!item.product_id) continue;
        const prod = products.find(p => p.id === item.product_id);
        if (!prod) continue;
        const newQty = prod.quantity_on_hand + item.quantity;
        let newStatus = "in_stock";
        if (newQty <= prod.min_stock_level) newStatus = "low_stock";
        await base44.entities.Product.update(item.product_id, { quantity_on_hand: newQty, status: newStatus });
      }
    }
    await base44.entities.Order.update(order.id, { status: next });
    loadData();
  };

  const handleSave = async (data) => {
    const total = (data.items || []).reduce((sum, i) => sum + (i.quantity * (i.unit_cost || 0)), 0);
    const newOrder = { ...data, total_cost: total, status: editing?.status || "draft" };

    try {
      if (editing) {
        // Optimistic update
        const updatedOrder = { ...editing, ...newOrder };
        setOrders(orders.map(o => o.id === editing.id ? updatedOrder : o));
        await base44.entities.Order.update(editing.id, newOrder);
      } else {
        // Optimistic add
        const created = await base44.entities.Order.create(newOrder);
        setOrders([created, ...orders]);
      }
    } catch (err) {
      // Rollback on error
      loadData();
    }
    setShowModal(false);
    setEditing(null);
  };

  return (
    <PullToRefresh onRefresh={loadData}>
    <div className="p-4 md:p-6 space-y-4">
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div>
          <h2 className="text-xl font-bold text-slate-800 dark:text-slate-100">Purchase Orders</h2>
          <p className="text-slate-500 dark:text-slate-400 text-sm">{orders.length} orders</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={generateOrder}
            disabled={generating}
            className="flex items-center gap-2 border border-amber-300 text-amber-700 bg-amber-50 hover:bg-amber-100 font-semibold text-sm px-3 py-2 rounded-xl transition-colors disabled:opacity-50"
          >
            {generating ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            {generating ? "Generating..." : "AI Reorder"}
          </button>
          <button
            onClick={() => { setEditing(null); setShowModal(true); }}
            className="flex items-center gap-2 bg-amber-400 hover:bg-amber-500 text-slate-900 font-semibold text-sm px-4 py-2 rounded-xl transition-colors"
          >
            <Plus className="w-4 h-4" /> New Order
          </button>
        </div>
      </div>

      {/* Orders List */}
      <div className="space-y-3">
        {loading ? (
          Array(3).fill(0).map((_, i) => (
            <div key={i} className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 h-20 animate-pulse" />
          ))
        ) : orders.length === 0 ? (
          <div className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 py-16 text-center">
            <ShoppingCart className="w-10 h-10 mx-auto text-slate-200 dark:text-slate-600 mb-2" />
            <p className="text-slate-400 text-sm">No orders yet</p>
            <p className="text-slate-400 text-xs mt-1">Create one manually or use AI Reorder for low stock</p>
          </div>
        ) : (
          orders.map(order => (
            <div key={order.id} className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-700 shadow-sm overflow-hidden">
              <div className="flex items-center gap-3 p-4">
                <div className="w-10 h-10 bg-slate-100 dark:bg-slate-700 rounded-xl flex items-center justify-center flex-shrink-0">
                  <Truck className="w-5 h-5 text-slate-500 dark:text-slate-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="font-semibold text-slate-800 dark:text-slate-100">{order.supplier}</p>
                  <p className="text-slate-400 dark:text-slate-500 text-xs">
                    {order.items?.length || 0} items • ${order.total_cost?.toFixed(2) || "0.00"}
                    {order.expected_delivery && ` • Due ${order.expected_delivery}`}
                  </p>
                </div>
                <span className={`text-xs px-2.5 py-1 rounded-full font-medium flex-shrink-0 ${statusStyle[order.status]}`}>
                  {order.status}
                </span>
                <button
                  onClick={() => setExpanded(expanded === order.id ? null : order.id)}
                  className="p-1.5 text-slate-400 hover:bg-slate-100 rounded-lg"
                >
                  {expanded === order.id ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                </button>
              </div>

              {expanded === order.id && (
                <div className="border-t border-slate-100 dark:border-slate-700 p-4 space-y-3">
                  {order.notes && (
                    <p className="text-slate-500 dark:text-slate-400 text-xs bg-slate-50 dark:bg-slate-900 px-3 py-2 rounded-xl">{order.notes}</p>
                  )}
                  <div className="space-y-1">
                    {(order.items || []).map((item, idx) => (
                      <div key={idx} className="flex items-center justify-between text-sm">
                        <span className="text-slate-700 dark:text-slate-300">{item.product_name}</span>
                        <span className="text-slate-500 dark:text-slate-400">×{item.quantity} @ ${item.unit_cost?.toFixed(2) || "—"}</span>
                      </div>
                    ))}
                  </div>
                  {nextStatus[order.status] && (
                    <button
                      onClick={() => advanceStatus(order)}
                      className="w-full py-2 bg-amber-400 hover:bg-amber-500 text-slate-900 rounded-xl text-sm font-bold transition-colors capitalize"
                    >
                      Mark as {nextStatus[order.status]}
                      {nextStatus[order.status] === "received" && " (Updates Inventory)"}
                    </button>
                  )}
                  {(order.status === "received" || order.status === "cancelled") && (
                    <button
                      onClick={() => removeOrder(order.id)}
                      className="w-full py-2 border border-red-200 text-red-600 hover:bg-red-50 rounded-xl text-sm font-medium transition-colors flex items-center justify-center gap-2"
                    >
                      <Trash2 className="w-4 h-4" /> Remove Order
                    </button>
                  )}
                </div>
              )}
            </div>
          ))
        )}
      </div>

      {/* Desktop modal */}
      {showModal && typeof window !== "undefined" && window.innerWidth >= 768 && (
        <OrderModal
          order={editing}
          products={products}
          onSave={handleSave}
          onClose={() => { setShowModal(false); setEditing(null); }}
        />
      )}

      {/* Mobile sheet */}
      {showModal && typeof window !== "undefined" && window.innerWidth < 768 && (
        <OrderSheet
          open={showModal}
          order={editing}
          products={products}
          onSave={handleSave}
          onClose={() => { setShowModal(false); setEditing(null); }}
        />
      )}
    </div>
    </PullToRefresh>
  );
}